export const GET_SERVICES = "GET_SERVICES";
export const CREATE_SERVICE = "CREATE_SERVICE";
export const CONFIRM_SERVICE = "CONFIRM_SERVICE";
export const USE_SERVICE = "USE_SERVICE";
export const GET_SERVICES_FOR_PROVIDER = "GET_SERVICES_FOR_PROVIDER";
export const SET_AVAILABILITY = "SET_AVAILABILITY";
export const DELETE_SERVICE = "DELETE_SERVICE";
export const IS_LOADING = "IS_LOADING";