export const CREATE_USER = "CREATE_USER";
export const LOGIN = "LOGIN";
export const ADD_PROVIDER_ATTRIBUTE = "ADD_PROVIDER_ATTRIBUTE";
export const UPDATE_USER_DETAILS = "UPDATE_USER_DETAILS";
export const GET_REQUEST_RESOLUTION = "GET_REQUEST_RESOLUTION";
export const GET_USED_SERVICES = "GET_USED_SERVICES";
export const IS_LOADING = "IS_LOADING";